In [2]:
import pandas as pd
import numpy as np

# Master Sheet 1

In [25]:
m1_df = pd.read_excel('M1.xlsx',  header=[1]) 
m1_df = pd.DataFrame(m1_df)

In [26]:
m1_df

,Unnamed: 0,Country,District,Sentinel Site,Date,MOSQUITO ID (Team),Morph ID Genus,Morph ID Species,PCR Number (Country Specific),PCR ID Genus,PCR ID Species,Sibling Species,Picture?,Prototype,Abdomen Status,Sex,Parity,Eliza Results
0,1.0,Uganda,Soroti,Awoja,2021-08-13 00:00:00,U-SR-01-0001,Anopheles,gambiae,NaN,Anopheles,gambiae,arabiensis,N,1409.0,SG,F,NaN,NEG
1,2.0,Uganda,Soroti,Awoja,2021-08-13 00:00:00,U-SR-01-0002,Anopheles,gambiae,NaN,NaN,NaN,NaN,N,NaN,FF,NaN,NaN,NEG
2,3.0,Uganda,Soroti,Awoja,2021-08-13 00:00:00,U-SR-01-0003,Anopheles,funestus,254,Anopheles,gambiae,arabiensis,N,NaN,G,F,NaN,NEG
3,4.0,Uganda,Soroti,Awoja,2021-08-13 00:00:00,U-SR-01-0004,Anopheles,funestus,86,Anopheles,gambiae,ss,N,NaN,SG,F,NaN,NEG
4,5.0,Uganda,Soroti,Awoja,2021-08-13 00:00:00,U-SR-01-0005,Anopheles,funestus,506,Anopheles,funestus,ss,N,307.0,G,F,NaN,NEG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1717,NaN,NaN,NaN,NaN,2021-05-10 00:00:00,Z-MA-02-0068,Culex,NaN,MI210068,Culex,NaN,NaN,N,NaN,NaN,F,NaN,NaN
1718,NaN,NaN,NaN,NaN,2021-05-10 00:00:00,Z-MA-02-0069,Culex,NaN,MI210069,Culex,NaN,NaN,N,NaN,NaN,F,NaN,NaN
1719,NaN,NaN,NaN,NaN,2021-05-10 00:00:00,Z-MA-02-0070,Culex,NaN,MI210070,Culex,NaN,NaN,N,NaN,NaN,F,NaN,NaN
1720,NaN,NaN,NaN,NaN,2021-05-10 00:00:00,Z-MA-02-0071,Culex,NaN,MI210071,Culex,NaN,NaN,N,NaN,NaN,F,NaN,NaN
1721,NaN,NaN,NaN,NaN,2021-05-10 00:00:00,Z-MA-02-0072,Culex,NaN,MI210072,Culex,NaN,NaN,N,NaN,NaN,F,NaN,NaN

In [27]:
m1_df[['MOSQUITO ID (Team)', 'Morph ID Species', 'Picture?', 'Abdomen Status', 'Sex']]

     MOSQUITO ID (Team) Morph ID Species Picture? Abdomen Status  Sex
0          U-SR-01-0001          gambiae        N             SG    F
1          U-SR-01-0002          gambiae        N             FF  NaN
2          U-SR-01-0003         funestus        N              G    F
3          U-SR-01-0004         funestus        N             SG    F
4          U-SR-01-0005         funestus        N              G    F
...                 ...              ...      ...            ...  ...
1717       Z-MA-02-0068              NaN        N            NaN    F
1718       Z-MA-02-0069              NaN        N            NaN    F
1719       Z-MA-02-0070              NaN        N            NaN    F
1720       Z-MA-02-0071              NaN        N            NaN    F
1721       Z-MA-02-0072              NaN        N            NaN    F

[1722 rows x 5 columns]

In [28]:
for col in m1_df.columns:
    print(col)

Unnamed: 0
Country
District
Sentinel Site
Date
MOSQUITO ID (Team)
Morph ID Genus
Morph ID Species
PCR Number (Country Specific)
PCR ID Genus
PCR ID Species
Sibling Species
Picture?
Prototype
Abdomen Status
Sex
Parity
Eliza Results

In [29]:
req_cols = ['MOSQUITO ID (Team)', 'Morph ID Species', 'Picture?', 'Abdomen Status', 'Sex']

In [33]:
m1_df.loc[:, req_cols]

     MOSQUITO ID (Team) Morph ID Species Picture? Abdomen Status  Sex
0          U-SR-01-0001          gambiae        N             SG    F
1          U-SR-01-0002          gambiae        N             FF  NaN
2          U-SR-01-0003         funestus        N              G    F
3          U-SR-01-0004         funestus        N             SG    F
4          U-SR-01-0005         funestus        N              G    F
...                 ...              ...      ...            ...  ...
1717       Z-MA-02-0068              NaN        N            NaN    F
1718       Z-MA-02-0069              NaN        N            NaN    F
1719       Z-MA-02-0070              NaN        N            NaN    F
1720       Z-MA-02-0071              NaN        N            NaN    F
1721       Z-MA-02-0072              NaN        N            NaN    F

[1722 rows x 5 columns]

In [41]:
not_null_m1_df = m1_df.loc[(~m1_df['MOSQUITO ID (Team)'].isnull()) & (~m1_df['Morph ID Species'].isnull()) & (~m1_df['Picture?'].isnull()) & (~m1_df['Abdomen Status'].isnull()) & (~m1_df['Sex'].isnull())]

In [43]:
m1_df_filtered = not_null_m1_df.loc[:, req_cols]
m1_df_filtered

     MOSQUITO ID (Team) Morph ID Species Picture? Abdomen Status Sex
0          U-SR-01-0001          gambiae        N             SG   F
2          U-SR-01-0003         funestus        N              G   F
3          U-SR-01-0004         funestus        N             SG   F
4          U-SR-01-0005         funestus        N              G   F
5          U-SR-01-0006         funestus        Y             SG   F
...                 ...              ...      ...            ...  ..
1645       Z-MA-01-0295          gambiae        Y             UF   F
1646       Z-MA-01-0296          rufipes        Y             UF   F
1647       Z-MA-01-0297          rufipes        Y             UF   F
1648       Z-MA-01-0298       longipalps        Y             UF   F
1649       Z-MA-01-0299          rufipes        Y             UF   F

[447 rows x 5 columns]

In [46]:
result_m1_df = m1_df_filtered[m1_df_filtered['Picture?'] == 'Y']

In [47]:
result_m1_df

     MOSQUITO ID (Team) Morph ID Species Picture? Abdomen Status Sex
5          U-SR-01-0006         funestus        Y             SG   F
8          U-SR-01-0009         funestus        Y              G   F
9          U-SR-01-0010         funestus        Y              G   F
13         U-SR-01-0014         funestus        Y             SG   F
15         U-SR-01-0016         funestus        Y              G   F
...                 ...              ...      ...            ...  ..
1645       Z-MA-01-0295          gambiae        Y             UF   F
1646       Z-MA-01-0296          rufipes        Y             UF   F
1647       Z-MA-01-0297          rufipes        Y             UF   F
1648       Z-MA-01-0298       longipalps        Y             UF   F
1649       Z-MA-01-0299          rufipes        Y             UF   F

[421 rows x 5 columns]

In [49]:
mosquito_ids = result_m1_df['MOSQUITO ID (Team)'].tolist()
print("Number of Mosquito's: ", len(mosquito_ids))
mosquito_ids

Number of Mosquito's:  421

['U-SR-01-0006',
 'U-SR-01-0009',
 'U-SR-01-0010',
 'U-SR-01-0014',
 'U-SR-01-0016',
 'U-SR-01-0026',
 'U-SR-01-0027',
 'U-SR-01-0029',
 'U-SR-01-0030',
 'U-SR-01-0034',
 'U-SR-01-0035',
 'U-SR-01-0039',
 'U-SR-01-0040',
 'U-SR-01-0069',
 'U-SR-01-0070',
 'U-SR-01-0071',
 'U-SR-01-0072',
 'U-SR-01-0073',
 'U-SR-01-0074',
 'U-SR-01-0075',
 'U-SR-01-0087',
 'U-SR-01-0090',
 'U-SR-01-0091',
 'U-SR-01-0092',
 'U-SR-01-0093',
 'U-SR-01-0094',
 'U-SR-01-0095',
 'U-SR-01-0096',
 'U-SR-01-0108',
 'U-SR-01-0111',
 'U-SR-01-0114',
 'U-SR-01-0115',
 'U-SR-01-0116',
 'U-SR-01-0118',
 'U-SR-01-0119',
 'U-SR-01-0120',
 'U-SR-01-0121',
 'U-SR-01-0122',
 'U-SR-01-0123',
 'U-SR-01-0127',
 'U-SR-01-0128',
 'U-SR-01-0129',
 'U-SR-01-0130',
 'U-SR-01-0131',
 'U-SR-01-0132',
 'U-SR-01-0133',
 'U-SR-01-0134',
 'U-SR-01-0135',
 'U-SR-01-0136',
 'U-SR-01-0137',
 'U-SR-01-0138',
 'U-SR-01-0179',
 'U-SR-01-0188',
 'U-SR-01-0190',
 'U-SR-01-0196',
 'U-SR-01-0235',
 'U-SR-01-0271',
 'U-SR-01-0272',
 'U-SR-01-0273',
 'U-SR-01-0274',
 'U-SR-01-0275',
 'U-SR-01-0283',
 'U-SR-01-0284',
 'U-SR-01-0286',
 'U-SR-01-0287',
 'U-SR-01-0288',
 'U-SR-01-0289',
 'U-SR-01-0290',
 'U-SR-01-0291',
 'U-SR-01-0296',
 'U-SR-01-0302',
 'U-SR-01-0303',
 'U-SR-01-0304',
 'U-SR-01-0305',
 'U-SR-01-0402',
 'U-SR-01-0403',
 'U-SR-01-0404',
 'U-SR-01-0405',
 'U-SR-01-0406',
 'U-SR-01-0407',
 'U-SR-01-0408',
 'U-SR-01-0409',
 'U-SR-01-0410',
 'U-SR-01-0412',
 'U-SR-01-0413',
 'U-SR-01-0414',
 'U-SR-01-0415',
 'U-SR-01-0421',
 'U-SR-01-0422',
 'U-SR-01-0423',
 'U-SR-01-0424',
 'U-SR-01-0430',
 'U-SR-01-0431',
 'U-SR-01-0432',
 'U-SR-01-0438',
 'U-SR-01-0443',
 'U-SR-01-0448',
 'U-SR-01-0449',
 'U-SR-01-0450',
 'U-SR-01-0451',
 'U-SR-01-0452',
 'U-SR-01-0453',
 'U-SR-01-0454',
 'U-SR-01-0455',
 'U-SR-01-0456',
 'U-SR-01-0466',
 'U-SR-01-0501',
 'U-SR-01-0519',
 'U-SR-01-0520',
 'U-SR-01-0521',
 'U-SR-01-0522',
 'U-SR-01-0524',
 'U-SR-01-0527',
 'U-SR-01-0528',
 'U-SR-01-0532',
 'U-SR-01-0535',
 'U-SR-01-0537',
 'U-SR-01-0540',
 'U-SR-01-0541',
 'U-SR-01-0542',
 'U-SR-01-0544',
 'U-SR-01-0566',
 'U-SR-01-0567',
 'U-SR-01-0571',
 'U-SR-01-0730',
 'U-SR-02-0002',
 'U-SR-02-0012',
 'U-SR-02-0021',
 'U-SR-02-0028',
 'U-SR-02-0029',
 'U-SR-02-0032',
 'U-SR-02-0042',
 'G-TM-05-0037',
 'G-TM-05-0038',
 'G-TM-05-0039',
 'G-TM-05-0040',
 'G-TM-05-0043',
 'G-TM-05-0059',
 'G-TM-05-0064',
 'G-TM-05-0065',
 'Z-MA-01-0001',
 'Z-MA-01-0002',
 'Z-MA-01-0003',
 'Z-MA-01-0006',
 'Z-MA-01-0007',
 'Z-MA-01-0008',
 'Z-MA-01-0009',
 'Z-MA-01-0010',
 'Z-MA-01-0011',
 'Z-MA-01-0012',
 'Z-MA-01-0013',
 'Z-MA-01-0014',
 'Z-MA-01-0015',
 'Z-MA-01-0016',
 'Z-MA-01-0017',
 'Z-MA-01-0018',
 'Z-MA-01-0020',
 'Z-MA-01-0021',
 'Z-MA-01-0022',
 'Z-MA-01-0023',
 'Z-MA-01-0024',
 'Z-MA-01-0025',
 'Z-MA-01-0027',
 'Z-MA-01-0028',
 'Z-MA-01-0029',
 'Z-MA-01-0030',
 'Z-MA-01-0031',
 'Z-MA-01-0032',
 'Z-MA-01-0033',
 'Z-MA-01-0034',
 'Z-MA-01-0035',
 'Z-MA-01-0036',
 'Z-MA-01-0037',
 'Z-MA-01-0038',
 'Z-MA-01-0039',
 'Z-MA-01-0040',
 'Z-MA-01-0041',
 'Z-MA-01-0042',
 'Z-MA-01-0043',
 'Z-MA-01-0044',
 'Z-MA-01-0045',
 'Z-MA-01-0046',
 'Z-MA-01-0047',
 'Z-MA-01-0048',
 'Z-MA-01-0049',
 'Z-MA-01-0050',
 'Z-MA-01-0051',
 'Z-MA-01-0052',
 'Z-MA-01-0053',
 'Z-MA-01-0054',
 'Z-MA-01-0055',
 'Z-MA-01-0056',
 'Z-MA-01-0059',
 'Z-MA-01-0060',
 'Z-MA-01-0061',
 'Z-MA-01-0062',
 'Z-MA-01-0063',
 'Z-MA-01-0064',
 'Z-MA-01-0065',
 'Z-MA-01-0066',
 'Z-MA-01-0067',
 'Z-MA-01-0068',
 'Z-MA-01-0069',
 'Z-MA-01-0070',
 'Z-MA-01-0071',
 'Z-MA-01-0072',
 'Z-MA-01-0073',
 'Z-MA-01-0074',
 'Z-MA-01-0076',
 'Z-MA-01-0077',
 'Z-MA-01-0078',
 'Z-MA-01-0079',
 'Z-MA-01-0080',
 'Z-MA-01-0081',
 'Z-MA-01-0082',
 'Z-MA-01-0083',
 'Z-MA-01-0084',
 'Z-MA-01-0085',
 'Z-MA-01-0086',
 'Z-MA-01-0087',
 'Z-MA-01-0088',
 'Z-MA-01-0089',
 'Z-MA-01-0092',
 'Z-MA-01-0094',
 'Z-MA-01-0095',
 'Z-MA-01-0096',
 'Z-MA-01-0097',
 'Z-MA-01-0098',
 'Z-MA-01-0099',
 'Z-MA-01-0100',
 'Z-MA-01-0101',
 'Z-MA-01-0102',
 'Z-MA-01-0103',
 'Z-MA-01-0104',
 'Z-MA-01-0105',
 'Z-MA-01-0106',
 'Z-MA-01-0107',
 'Z-MA-01-0108',
 'Z-MA-01-0109',
 'Z-MA-01-0110',
 'Z-MA-01-0111',
 'Z-MA-01-0112',
 'Z-MA-01-0113',
 'Z-MA-01-0114',
 'Z-MA-01-0115',
 'Z-MA-01-0116',
 'Z-MA-01-0117',
 'Z-MA-01-0118',
 'Z-MA-01-0119',
 'Z-MA-01-0120',
 'Z-MA-01-0121',
 'Z-MA-01-0122',
 'Z-MA-01-0123',
 'Z-MA-01-0124',
 'Z-MA-01-0125',
 'Z-MA-01-0126',
 'Z-MA-01-0127',
 'Z-MA-01-0128',
 'Z-MA-01-0129',
 'Z-MA-01-0130',
 'Z-MA-01-0131',
 'Z-MA-01-0132',
 'Z-MA-01-0134',
 'Z-MA-01-0135',
 'Z-MA-01-0136',
 'Z-MA-01-0137',
 'Z-MA-01-0138',
 'Z-MA-01-0139',
 'Z-MA-01-0140',
 'Z-MA-01-0141',
 'Z-MA-01-0142',
 'Z-MA-01-0143',
 'Z-MA-01-0144',
 'Z-MA-01-0145',
 'Z-MA-01-0146',
 'Z-MA-01-0147',
 'Z-MA-01-0148',
 'Z-MA-01-0149',
 'Z-MA-01-0150',
 'Z-MA-01-0151',
 'Z-MA-01-0152',
 'Z-MA-01-0153',
 'Z-MA-01-0154',
 'Z-MA-01-0155',
 'Z-MA-01-0156',
 'Z-MA-01-0157',
 'Z-MA-01-0158',
 'Z-MA-01-0159',
 'Z-MA-01-0160',
 'Z-MA-01-0161',
 'Z-MA-01-0162',
 'Z-MA-01-0163',
 'Z-MA-01-0164',
 'Z-MA-01-0165',
 'Z-MA-01-0166',
 'Z-MA-01-0167',
 'Z-MA-01-0168',
 'Z-MA-01-0169',
 'Z-MA-01-0170',
 'Z-MA-01-0171',
 'Z-MA-01-0172',
 'Z-MA-01-0174',
 'Z-MA-01-0175',
 'Z-MA-01-0176',
 'Z-MA-01-0177',
 'Z-MA-01-0178',
 'Z-MA-01-0179',
 'Z-MA-01-0180',
 'Z-MA-01-0181',
 'Z-MA-01-0182',
 'Z-MA-01-0183',
 'Z-MA-01-0184',
 'Z-MA-01-0185',
 'Z-MA-01-0186',
 'Z-MA-01-0187',
 'Z-MA-01-0188',
 'Z-MA-01-0189',
 'Z-MA-01-0190',
 'Z-MA-01-0191',
 'Z-MA-01-0192',
 'Z-MA-01-0193',
 'Z-MA-01-0194',
 'Z-MA-01-0195',
 'Z-MA-01-0196',
 'Z-MA-01-0197',
 'Z-MA-01-0199',
 'Z-MA-01-0200',
 'Z-MA-01-0201',
 'Z-MA-01-0202',
 'Z-MA-01-0203',
 'Z-MA-01-0204',
 'Z-MA-01-0205',
 'Z-MA-01-0206',
 'Z-MA-01-0207',
 'Z-MA-01-0208',
 'Z-MA-01-0209',
 'Z-MA-01-0210',
 'Z-MA-01-0211',
 'Z-MA-01-0212',
 'Z-MA-01-0214',
 'Z-MA-01-0215',
 'Z-MA-01-0216',
 'Z-MA-01-0217',
 'Z-MA-01-0218',
 'Z-MA-01-0219',
 'Z-MA-01-0220',
 'Z-MA-01-0221',
 'Z-MA-01-0222',
 'Z-MA-01-0223',
 'Z-MA-01-0224',
 'Z-MA-01-0225',
 'Z-MA-01-0226',
 'Z-MA-01-0227',
 'Z-MA-01-0228',
 'Z-MA-01-0229',
 'Z-MA-01-0230',
 'Z-MA-01-0231',
 'Z-MA-01-0232',
 'Z-MA-01-0233',
 'Z-MA-01-0234',
 'Z-MA-01-0235',
 'Z-MA-01-0236',
 'Z-MA-01-0237',
 'Z-MA-01-0238',
 'Z-MA-01-0239',
 'Z-MA-01-0240',
 'Z-MA-01-0241',
 'Z-MA-01-0242',
 'Z-MA-01-0243',
 'Z-MA-01-0244',
 'Z-MA-01-0245',
 'Z-MA-01-0246',
 'Z-MA-01-0247',
 'Z-MA-01-0248',
 'Z-MA-01-0249',
 'Z-MA-01-0250',
 'Z-MA-01-0251',
 'Z-MA-01-0252',
 'Z-MA-01-0253',
 'Z-MA-01-0254',
 'Z-MA-01-0255',
 'Z-MA-01-0256',
 'Z-MA-01-0257',
 'Z-MA-01-0258',
 'Z-MA-01-0259',
 'Z-MA-01-0260',
 'Z-MA-01-0261',
 'Z-MA-01-0262',
 'Z-MA-01-0263',
 'Z-MA-01-0264',
 'Z-MA-01-0265',
 'Z-MA-01-0266',
 'Z-MA-01-0267',
 'Z-MA-01-0268',
 'Z-MA-01-0270',
 'Z-MA-01-0271',
 'Z-MA-01-0274',
 'Z-MA-01-0275',
 'Z-MA-01-0276',
 'Z-MA-01-0277',
 'Z-MA-01-0278',
 'Z-MA-01-0279',
 'Z-MA-01-0280',
 'Z-MA-01-0281',
 'Z-MA-01-0282',
 'Z-MA-01-0283',
 'Z-MA-01-0284',
 'Z-MA-01-0286',
 'Z-MA-01-0287',
 'Z-MA-01-0288',
 'Z-MA-01-0289',
 'Z-MA-01-0290',
 'Z-MA-01-0291',
 'Z-MA-01-0292',
 'Z-MA-01-0293',
 'Z-MA-01-0294',
 'Z-MA-01-0295',
 'Z-MA-01-0296',
 'Z-MA-01-0297',
 'Z-MA-01-0298',
 'Z-MA-01-0299']

In [54]:
print("Morph ID Species: ", result_m1_df['Morph ID Species'].value_counts().to_dict())
print("Abdomen Status: ", result_m1_df['Abdomen Status'].value_counts().to_dict())
print("Number of Males and Females: ", result_m1_df['Sex'].value_counts().to_dict())

Morph ID Species:  {'squamosus': 155, 'funestus': 117, 'gambiae': 114, 'rufipes': 23, 'coustani': 9, 'longipalps': 2, 'pretoriensis': 1}
Abdomen Status:  {'UF': 251, 'G': 75, 'SG': 58, 'FF': 22, 'sugar water': 15}
Number of Males and Females:  {'F': 406, 'M': 15}

# Master Sheet 2

In [55]:
m2_df = pd.read_excel('M2.xlsx',  header=[1]) 
m2_df = pd.DataFrame(m2_df)
m2_df

,mosquito_id,Country,City,Site,Date,specimen_image_1,specimen_image_2,specimen_image_3,morph_id_genus,morph_id_genus_other,...,pcr_present,pcr_id_genus,pcr_id_genus_other,pcr_id_aedes_species,pcr_id_anopheles_species,pcr_id_species_other,pcr_id_sibling,additional_note,PARENT_KEY,KEY
0,G031B,Uganda,Bugiri,Buboki,2022-04-02,1648900605929.jpg,1648900637908.jpg,1648900654087.jpg,Anopheles,NaN,...,later,NaN,NaN,NaN,NaN,NaN,NaN,NaN,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9/hh_r...
1,G032B,Uganda,Bugiri,Buboki,2022-04-02,1648900707180.jpg,1648900718477.jpg,1648900736152.jpg,Anopheles,NaN,...,later,NaN,NaN,NaN,NaN,NaN,NaN,NaN,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9/hh_r...
2,G033B,Uganda,Bugiri,Buboki,2022-04-02,1648900875092.jpg,1648900888835.jpg,1648900905444.jpg,Anopheles,NaN,...,later,NaN,NaN,NaN,NaN,NaN,NaN,NaN,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9/hh_r...
3,G034B,Uganda,Bugiri,Buboki,2022-04-02,1648900946763.jpg,1648900961718.jpg,1648900978547.jpg,Anopheles,NaN,...,later,NaN,NaN,NaN,NaN,NaN,NaN,NaN,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9/hh_r...
4,B035B,Uganda,Bugiri,Buboki,2022-04-02,1648901102036.jpg,1648901120450.jpg,1648901136984.jpg,Anopheles,NaN,...,later,NaN,NaN,NaN,NaN,NaN,NaN,NaN,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9,uuid:cd9fe629-f8a5-4dc0-8e7e-2eee17bf50b9/hh_r...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,NaN,NaN,NaN,NaN,NaT,1643193598508.jpg,1643193634018.jpg,1643193701849.jpg,Anopheles,\n,...,later,\n,\n,\n,\n,\n,\n,Na,uuid:b8df0317-2b65-4d17-afe9-fd7ed0f52609,uuid:b8df0317-2b65-4d17-afe9-fd7ed0f52609/hh_r...
710,NaN,NaN,NaN,NaN,NaT,1643192970690.jpg,1643193019263.jpg,1643193065582.jpg,Anopheles,\n,...,later,\n,\n,\n,\n,\n,\n,NaN,uuid:958e8fc8-cb3e-4214-930d-80227b14b4b3,uuid:958e8fc8-cb3e-4214-930d-80227b14b4b3/hh_r...
711,NaN,NaN,NaN,NaN,NaT,1643193284792.jpg,1643193320535.jpg,1643193372510.jpg,Anopheles,\n,...,later,\n,\n,\n,\n,\n,\n,Na,uuid:958e8fc8-cb3e-4214-930d-80227b14b4b3,uuid:958e8fc8-cb3e-4214-930d-80227b14b4b3/hh_r...
712,NaN,NaN,NaN,NaN,NaT,1642774690032.jpg,1642774707378.jpg,1642774718884.jpg,Anopheles,\n,...,no,\n,\n,\n,\n,\n,\n,NaN,uuid:8b60ca61-4660-4ff6-af4b-7e1cfd79b967,uuid:8b60ca61-4660-4ff6-af4b-7e1cfd79b967/hh_r...
713,NaN,NaN,NaN,NaN,NaT,1642522324618.jpg,1642522874070.png,1642522881150.jpg,Mansonia,\n,...,no,\n,\n,\n,\n,\n,\n,This is a test,uuid:2b8a3ec6-869d-4a63-be8b-a3e8de1555f8,uuid:2b8a3ec6-869d-4a63-be8b-a3e8de1555f8/hh_r...

In [59]:
req_cols_2 = ['specimen_image_1', 'specimen_image_2', 'specimen_image_3', 'morph_id_anopheles_species', 'specimen_characteristics', 'specimen_gender']

In [63]:
m2_req_col_df = m2_df.loc[:, req_cols_2]

In [64]:
result_m2_df = m2_req_col_df.dropna()
result_m2_df

,specimen_image_1,specimen_image_2,specimen_image_3,morph_id_anopheles_species,specimen_characteristics,specimen_gender
0,1648900605929.jpg,1648900637908.jpg,1648900654087.jpg,gambiae,UF,F
1,1648900707180.jpg,1648900718477.jpg,1648900736152.jpg,gambiae,UF,F
2,1648900875092.jpg,1648900888835.jpg,1648900905444.jpg,gambiae,UF,F
3,1648900946763.jpg,1648900961718.jpg,1648900978547.jpg,gambiae,UF,M
4,1648901102036.jpg,1648901120450.jpg,1648901136984.jpg,gambiae,UF,F
...,...,...,...,...,...,...
709,1643193598508.jpg,1643193634018.jpg,1643193701849.jpg,gambiae,UF,F
710,1643192970690.jpg,1643193019263.jpg,1643193065582.jpg,gambiae,SG,F
711,1643193284792.jpg,1643193320535.jpg,1643193372510.jpg,gambiae,SG,F
712,1642774690032.jpg,1642774707378.jpg,1642774718884.jpg,funestus,UF,M
713,1642522324618.jpg,1642522874070.png,1642522881150.jpg,\n,G,F

In [66]:
print("Morph ID Species: ", result_m2_df['morph_id_anopheles_species'].value_counts().to_dict())
print("Abdomen Status: ", result_m2_df['specimen_characteristics'].value_counts().to_dict())
print("Number of Males and Females: ", result_m2_df['specimen_gender'].value_counts().to_dict())

Morph ID Species:  {'funestus': 238, 'gambiae': 223, 'other': 34, '\n': 10, 'pharoensis': 3}
Abdomen Status:  {'UF': 440, 'SG': 26, 'G': 24, 'FF': 18}
Number of Males and Females:  {'F': 427, 'M': 81}